# Generated by Django 4.0.5 on 2022-07-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ja',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(blank=True, help_text='Insert here the text of your Post, however you can leave it empty if you wish so', null=True, verbose_name='Текст поста (необязательно)'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_fr',
            field=models.TextField(blank=True, help_text='Insert here the text of your Post, however you can leave it empty if you wish so', null=True, verbose_name='Текст поста (необязательно)'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ja',
            field=models.TextField(blank=True, help_text='Insert here the text of your Post, however you can leave it empty if you wish so', null=True, verbose_name='Текст поста (необязательно)'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(blank=True, help_text='Insert here the text of your Post, however you can leave it empty if you wish so', null=True, verbose_name='Текст поста (необязательно)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ja',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='slug is set up automatically', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, help_text='Insert here the text of your Post, however you can leave it empty if you wish so', null=True, verbose_name='Текст поста (необязательно)'),
        ),
    ]
