# Generated by Django 4.0.5 on 2022-08-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_category_name_en_us_category_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_zh_CN',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_zh_CN',
            field=models.TextField(blank=True, help_text='Insert here the text of your Post, however you can leave it empty if you wish so', null=True, verbose_name='Текст поста (необязательно)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_zh_CN',
            field=models.CharField(max_length=128, null=True, verbose_name='Заголовок поста'),
        ),
    ]
