# Generated by Django 4.0.5 on 2022-08-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_categorysubscribe_category_subscriber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubscribe',
            old_name='subscriber_through',
            new_name='subscriber',
        ),
    ]
